package com.example.jobup.entities;

public enum NotificationType {
    POST_LIKED, POST_COMMENTED, POST_SAVED,
    PROPOSAL_RECEIVED, PROPOSAL_ACCEPTED, PROPOSAL_DECLINED,
    DEAL_CONFIRMED, DEAL_IN_PROGRESS, DEAL_COMPLETED, DEAL_CANCELLED,
    RATING_ADDED
}
