/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface JobDealDto { 
    id?: string;
    proposalId?: string;
    chatId?: string;
    clientId?: string;
    workerId?: string;
    title?: string;
    description?: string;
    durationMinutes?: number;
    price?: number;
    location?: string;
    scheduledAt?: string;
    status?: JobDealDto.StatusEnum;
    confirmedAt?: string;
    completedAt?: string;
    createdAt?: string;
    updatedAt?: string;
}
export namespace JobDealDto {
    export type StatusEnum = 'CONFIRMED' | 'IN_PROGRESS' | 'COMPLETED' | 'CANCELLED';
    export const StatusEnum = {
        Confirmed: 'CONFIRMED' as StatusEnum,
        InProgress: 'IN_PROGRESS' as StatusEnum,
        Completed: 'COMPLETED' as StatusEnum,
        Cancelled: 'CANCELLED' as StatusEnum
    };
}


