/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SendMessageRequest { 
    senderId?: string;
    senderName?: string;
    senderType?: SendMessageRequest.SenderTypeEnum;
    receiverId?: string;
    receiverName?: string;
    receiverType?: SendMessageRequest.ReceiverTypeEnum;
    content?: string;
}
export namespace SendMessageRequest {
    export type SenderTypeEnum = 'CLIENT' | 'WORKER';
    export const SenderTypeEnum = {
        Client: 'CLIENT' as SenderTypeEnum,
        Worker: 'WORKER' as SenderTypeEnum
    };
    export type ReceiverTypeEnum = 'CLIENT' | 'WORKER';
    export const ReceiverTypeEnum = {
        Client: 'CLIENT' as ReceiverTypeEnum,
        Worker: 'WORKER' as ReceiverTypeEnum
    };
}


