/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateStatusRequest { 
    status?: UpdateStatusRequest.StatusEnum;
}
export namespace UpdateStatusRequest {
    export type StatusEnum = 'PENDING' | 'ACCEPTED' | 'DECLINED' | 'NEGOTIATED';
    export const StatusEnum = {
        Pending: 'PENDING' as StatusEnum,
        Accepted: 'ACCEPTED' as StatusEnum,
        Declined: 'DECLINED' as StatusEnum,
        Negotiated: 'NEGOTIATED' as StatusEnum
    };
}


