/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ChatMessageDto { 
    id?: string;
    chatId?: string;
    senderId?: string;
    senderName?: string;
    senderType?: string;
    receiverId?: string;
    receiverName?: string;
    receiverType?: string;
    content?: string;
    timestamp?: string;
    messageType?: ChatMessageDto.MessageTypeEnum;
    proposalId?: string;
}
export namespace ChatMessageDto {
    export const MessageTypeEnum = {
        Text: 'TEXT',
        Proposal: 'PROPOSAL',
        ProposalResponse: 'PROPOSAL_RESPONSE',
        JobConfirmed: 'JOB_CONFIRMED',
        JobCompleted: 'JOB_COMPLETED',
        Rating: 'RATING'
    } as const;
    export type MessageTypeEnum = typeof MessageTypeEnum[keyof typeof MessageTypeEnum];
}


