/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CommentDto { 
    id?: string;
    authorId?: string;
    authorName?: string;
    content?: string;
    createdAt?: string;
}

