/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * File upload response DTO
 */
export interface FileUploadResponseDto { 
    /**
     * File ID
     */
    id?: string;
    /**
     * Original file name
     */
    originalFileName?: string;
    /**
     * File download URL
     */
    downloadUrl?: string;
    /**
     * File content type
     */
    contentType?: string;
    /**
     * File size in bytes
     */
    fileSize?: number;
    /**
     * File type
     */
    fileType?: FileUploadResponseDto.FileTypeEnum;
    /**
     * File category
     */
    category?: FileUploadResponseDto.CategoryEnum;
    /**
     * Upload timestamp
     */
    uploadedAt?: string;
    /**
     * Image width (for images only)
     */
    width?: number;
    /**
     * Image height (for images only)
     */
    height?: number;
    /**
     * Owner ID
     */
    ownerId?: string;
}
export namespace FileUploadResponseDto {
    export const FileTypeEnum = {
        ImageJpeg: 'IMAGE_JPEG',
        ImagePng: 'IMAGE_PNG',
        ImageGif: 'IMAGE_GIF',
        DocumentPdf: 'DOCUMENT_PDF',
        DocumentDoc: 'DOCUMENT_DOC',
        DocumentDocx: 'DOCUMENT_DOCX'
    } as const;
    export type FileTypeEnum = typeof FileTypeEnum[keyof typeof FileTypeEnum];
    export const CategoryEnum = {
        ProfilePicture: 'PROFILE_PICTURE',
        JobAttachment: 'JOB_ATTACHMENT',
        WorkerPortfolio: 'WORKER_PORTFOLIO',
        WorkerCertificate: 'WORKER_CERTIFICATE'
    } as const;
    export type CategoryEnum = typeof CategoryEnum[keyof typeof CategoryEnum];
}


