/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface JobDealDto { 
    id?: string;
    proposalId?: string;
    chatId?: string;
    clientId?: string;
    workerId?: string;
    title?: string;
    description?: string;
    duration?: number;
    price?: number;
    location?: string;
    scheduledTime?: string;
    confirmedAt?: string;
    status?: JobDealDto.StatusEnum;
    rating?: number;
    review?: string;
    completedAt?: string;
}
export namespace JobDealDto {
    export const StatusEnum = {
        Confirmed: 'CONFIRMED',
        InProgress: 'IN_PROGRESS',
        Completed: 'COMPLETED',
        Cancelled: 'CANCELLED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


