/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface JobProposalDto { 
    id?: string;
    chatId?: string;
    senderId?: string;
    senderName?: string;
    senderType?: string;
    receiverId?: string;
    receiverName?: string;
    receiverType?: string;
    title?: string;
    description?: string;
    duration?: number;
    price?: number;
    location?: string;
    scheduledTime?: string;
    createdAt?: string;
    status?: JobProposalDto.StatusEnum;
}
export namespace JobProposalDto {
    export const StatusEnum = {
        Pending: 'PENDING',
        Accepted: 'ACCEPTED',
        Declined: 'DECLINED',
        Negotiated: 'NEGOTIATED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


