/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CommentDto } from './commentDto';


export interface JobPostDto { 
    id?: string;
    title?: string;
    description?: string;
    location?: string;
    createdAt?: string;
    createdById?: string;
    createdByName?: string;
    likes?: Array<string>;
    savedBy?: Array<string>;
    comments?: Array<CommentDto>;
    attachmentFileIds?: Array<string>;
}

