/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface NotificationDto { 
    id?: string;
    recipientId?: string;
    recipientName?: string;
    senderId?: string;
    senderName?: string;
    postId?: string;
    postTitle?: string;
    type?: NotificationDto.TypeEnum;
    message?: string;
    actionUrl?: string;
    createdAt?: string;
    read?: boolean;
}
export namespace NotificationDto {
    export const TypeEnum = {
        PostLiked: 'POST_LIKED',
        PostCommented: 'POST_COMMENTED',
        PostSaved: 'POST_SAVED',
        ProposalReceived: 'PROPOSAL_RECEIVED',
        ProposalAccepted: 'PROPOSAL_ACCEPTED',
        ProposalDeclined: 'PROPOSAL_DECLINED'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


