/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateStatusRequest { 
    status?: UpdateStatusRequest.StatusEnum;
}
export namespace UpdateStatusRequest {
    export const StatusEnum = {
        Pending: 'PENDING',
        Accepted: 'ACCEPTED',
        Declined: 'DECLINED',
        Negotiated: 'NEGOTIATED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


