/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * DTO used to update user information
 */
export interface UserUpdateRequestDto { 
    username?: string;
    email?: string;
    newPassword?: string;
    currentPassword?: string;
}

