/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * DTO used to create a new worker
 */
export interface WorkerCreateDto { 
    jobType?: string;
    phoneNumber?: string;
    location?: string;
    description?: string;
    /**
     * User ID who becomes a worker
     */
    userId?: string;
}

