/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RatingDistribution } from './ratingDistribution';


export interface WorkerRatingStatsDto { 
    workerId?: string;
    averageRating?: number;
    totalRatings?: number;
    totalCompletedJobs?: number;
    ratingDistribution?: RatingDistribution;
}

