/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * DTO returned in responses to the frontend
 */
export interface WorkerResponseDto { 
    id?: string;
    fullName?: string;
    jobType?: string;
    phoneNumber?: string;
    location?: string;
    rating?: number;
    description?: string;
}

