/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * DTO used to update an existing worker
 */
export interface WorkerUpdateDto { 
    fullName?: string;
    jobType?: string;
    location?: string;
    phoneNumber?: string;
    description?: string;
}

